version: '2'

services:
  gitlab:
    image: gitlab/gitlab-ce:12.10.3-ce.0
    container_name: git.breweryda.com
    restart: unless-stopped
    hostname: git.breweryda.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.breweryda.com'
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/my_cert.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/my_cert.key"
        nginx['http2_enabled'] = false
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
      - /etc/ssl/certs_path:/etc/gitlab/ssl
    networks:
      - shared_network

volumes:
  gitlab_config:
    external: true
  gitlab_logs:
    external: true
  gitlab_data:
    external: true

networks:
  shared_network:
    external: true  