#!/bin/bash

for CONTAINER in $(docker container ls -q)
do
	docker container stop $CONTAINER
    docker container rm $CONTAINER
done

docker system prune -a --force

docker volume prune --force

sudo apt-get purge -y docker-engine docker docker.io docker-ce docker-ce-cli
sudo apt-get autoremove -y --purge docker-engine docker docker.io docker-ce docker-ce-cli

sudo rm -rf /var/lib/docker /etc/docker
sudo rm /etc/apparmor.d/docker
sudo groupdel docker
sudo rm -rf /var/run/docker.sock