version: '2'

services:
  portainer:
    image: portainer/portainer:1.23.2
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - /etc/ssl/certs_path:/certs
    networks:
      - shared_network
    command: 
      --ssl
      --sslcert /certs/my_cert.crt
      --sslkey /certs/my_cert.key

volumes:
  portainer_data:
    external: true

networks:
  shared_network:
    external: true