version: '2'

services:
  portainer:
    image: portainer/portainer:1.23.2
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - shared_network

volumes:
  portainer_data:
    external: true

networks:
  shared_network:
    external: true