version: '2'

services:
  gitlab:
    image: gitlab/gitlab-ce:12.4.3-ce.0
    container_name: git.breweryda.com
    restart: unless-stopped
    hostname: git.breweryda.com    
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    environment: 
      VIRTUAL_HOST: git.breweryda.com
    networks:
      - shared_network

  portainer:
    image: portainer/portainer:1.22.1
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - /etc/ssl/certs_path:/certs
    networks:
      - shared_network
    command: 
      --ssl
      --sslcert /certs/my_cert.crt
      --sslkey /certs/my_cert.key

  nginx:
    image: jwilder/nginx-proxy:0.7.0
    container_name: nginx
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
        - 80:80
    networks:
      - shared_network

volumes:
  gitlab_config:
    external: true
  gitlab_logs:
    external: true
  gitlab_data:
    external: true
  portainer_data:
    external: true

networks:
  shared_network:
    external: true