version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy:0.7.0
    container_name: nginx
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
        - 80:80
    networks:
      - shared_network

networks:
  shared_network:
    external: true