version: '2'

services:
  gitlab:
    image: gitlab/gitlab-ce:12.4.3-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: git.nu12.xyz    
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    environment: 
      VIRTUAL_HOST: git.nu12.xyz
    networks:
      - shared_network

volumes:
  gitlab_config:
    external: true
  gitlab_logs:
    external: true
  gitlab_data:
    external: true

networks:
  shared_network:
    external: true