version: '2'

services:
  nginx:
    image: nginx:1.17.10
    container_name: nginx
    restart: unless-stopped 
    volumes: 
      - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs_path:/certs_path:ro
    ports:
        - 80:80
        - 443:443
    networks:
      - shared_network

networks:
  shared_network:
    external: true