version: '2'

services:
  pgadmin:
    image: dpage/pgadmin4:4.10
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    networks:
      - shared_network
    ports:
      - 9004:80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:
    external: true

networks:
  shared_network:
    external: true